version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules  # prevent host's node_modules from leaking in
      - G:/Videos:/app/videos
    command: npm run dev  
    environment:
      - CHOKIDAR_USEPOLLING=true  # optional: improve file watching inside Docker
    env_file:
      - ./frontend/.env 
    restart: unless-stopped     

volumes:
  node_modules:
