version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    restart: unless-stopped 

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"      
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
      - G:/Videos:/app/videos
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    command: npm run dev
    restart: unless-stopped

  tus:
    build:
      context: ./tus
    volumes:
      - ./tus:/app
      - node_modules_tus:/app/node_modules
      - G:/Videos:/app/videos
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./tus/.env      
    command: npm run dev
    restart: unless-stopped

volumes:
  node_modules_frontend:
  node_modules_backend:
  node_modules_tus:
